---
- name: Create group
  hosts: localhost
  tasks:
        - name: Create a group
          group: name=deploy state=present
        - name: Create a group user
          user: name=deploy-user group=deploy state=present

...
