---
- name: This sets up an httpd webserver
  hosts: localhost
  vars:
    myname: "Som in playbook"
    package: "apache2"
    service: "apache2"
  vars_files:
    - "var.yaml"
  vars_prompt:
    - name: "myname"
      prompt: "What is your name?"
      private: no

  tasks:
  - name: Install the httpd apps
    apt: name={{package}}
  - name: start the httpd service
    service: name={{service}} state=started
  - name: Find the status of httpd service
    shell: "find *.txt"
    args:
      chdir: "/home/som/Desktop/Ansible/playbook"
    register: myname
  - debug:
       msg: "My name is {{myname}}"

...



ansible-playbook playbook_vars.yaml -e myname=somatcli


# Varible precedence
1. Using external varible at cmd line
2. Runtime
3. cmdline input
4. external file
5. in playbook
