---
- name: This sets up an httpd webserver
  hosts: localhost
  become: true
  vars:
    myname: "rajesh kumar in playbook"

  tasks:
  - name: Update all packages to the latest version
    apt: upgrade=dist
  - name: Install the httpd apps
    apt: name=apache2 state=present
  - name: start the httpd service
    service: name=apache2 state=started
  - name: copy a file
    copy: dest=/var/www/html/ src="/home/ubuntu/index.j2"
  - debug: 
      msg: "My Name is {{myname}}"
...

