---
      - name: Create a file
        file: path=/var/www/html/index.html state=touch mode='0777'
      - name: Copy a file
        copy: src=/home/som/Desktop/Ansible/secound.html dest=/var/www/html/secound.html
...
