---
- name: Install and start an apache2
  tasks:
       - name: Install apache2
         apt: name=apache2 state=present
       - name: Start the apache service
         service: name=apache2 state=started
...
