---
- name: DEV and QA install apache
  hosts: dev
  become: yes
  tasks:
  - name: Install the apache2
    apt: name={{package}}
  - name: copy port config file
    copy: dest=/etc/apache2/ports.conf src="/home/som/Desktop/Ansible/template/ports.j2"
  - name: start the apache2 service
    service: name={{service}} state=started
  - template:
      src: ports.j2
      dest: /etc/apache2/ports.conf

...
